### ISSUE TITLE
Custom Delimter is ignored when using multiple fields

### ISSUE THREAD

**Issue by milesleif** [texnixe/kirby3-similar#1]
Hi there,

I found that in `src/Similar.php` on line `57` the `split()`-method is used without taking the given `$limiter` into account. That makes it impossible to use a limiter other than `,` when using multiple fields at the same time.

Branch is `master`. 

Easy fix, but worth fixing. :)

**Comment by texnixe** [comment]
Thanks for reporting, fixed now.
