### ISSUE TITLE
PHP 8.2 compatibility

### ISSUE THREAD

**Issue by mynameisfreedom** [texnixe/kirby3-similar#5]
Hi @texnixe!

Just to remind you when you have time make Kirby3 Similar plugin compatible with PHP 8.2. 

Thank you!

**Comment by fsennj** [comment]
any news on 8.2? 

Getting that error:
Creation of dynamic property Kirby\Cms\Page::$jaccardIndex is deprecated

    protected function filterByJaccardIndex(array $searchItems)
    {
        return $this->index->map(function ($item) use ($searchItems) {
            **$item->jaccardIndex = $this->calculateSimilarityIndex($item, $searchItems);**
<img width="1276" alt="Bildschirmfoto 2023-05-07 um 19 50 11" src="https://user-images.githubusercontent.com/61477285/236694141-1da7e769-d6f2-4d39-8127-2d56273c2ee3.png">

            return $item;
        })->filterBy('jaccardIndex', '>=', $this->threshold)->sortBy('jaccardIndex', 'desc');
    }

**Comment by tobimori** [comment]
Hi @texnixe, you'll have to create a new release (3.0.1) for the version requirement in aa05686a091999531f3b13b50e4c7cf482bede9d to apply to composer installations. Could you kindly do that?
